Task 3 7 implement ui for entering a game
DavidRisch/kicker pull request #25
Opened 2020-05-11 14:11 UTC by mariusalexander

2020-05-11 14:57 UTC, DavidRisch requested changes
Please also look at the changes I made in 456b994d and cf2215e6

2020-05-11 14:57 UTC, DavidRisch commented on page/enter_game.js
> +    res.end(html)
Please use  `html_creator`

2020-05-11 14:57 UTC, DavidRisch commented on js/enter_game.js
> +module.exports = {
Files in `js/` are not node modules, they should not contain `module.exports`

2020-05-11 14:57 UTC, DavidRisch commented on api/api.js
> +        require('../js/enter_game').process(body.playerA1, body.playerA2, body.playerB1, body.playerB2, body.goalsA, body.goalsB)
Api methods should be located in the `api/`directory

2020-05-12 11:16 UTC, mariusalexander commented
ready to merge?

2020-05-12 11:32 UTC, merged